"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { AcademicDivision, CurrentUser, Institution, Subject, apiRequest } from "../../../lib/api";

export default function SubjectManagementPage() {
  const [user,setUser]=useState<CurrentUser|null>(null), [institutions,setInstitutions]=useState<Institution[]>([]), [divisions,setDivisions]=useState<AcademicDivision[]>([]), [subjects,setSubjects]=useState<Subject[]>([]);
  const [institutionId,setInstitutionId]=useState(""), [divisionId,setDivisionId]=useState(""), [busy,setBusy]=useState(false), [notice,setNotice]=useState("");
  useEffect(()=>{Promise.all([apiRequest<CurrentUser>("/api/v1/auth/me"),apiRequest<Institution[]>("/api/v1/institutions")]).then(([me,s])=>{setUser(me);setInstitutions(s);setInstitutionId(s[0]?.id??"");}).catch((e:Error)=>setNotice(e.message));},[]);
  useEffect(()=>{if(!institutionId)return;Promise.all([apiRequest<AcademicDivision[]>(`/api/v1/academic-divisions?institution_id=${institutionId}`),apiRequest<Subject[]>(`/api/v1/subjects?institution_id=${institutionId}`)]).then(([d,s])=>{setDivisions(d);setSubjects(s);setDivisionId(c=>d.some(x=>x.id===c)?c:d[0]?.id??"");}).catch((e:Error)=>setNotice(e.message));},[institutionId]);
  const institutionWide=useMemo(()=>Boolean(user&&(user.is_platform_admin||user.assignments.some(a=>a.institution_id===institutionId&&a.scope_type==="institution"&&["PRINCIPAL","SCHOOL_ADMIN"].includes(a.role_code)))),[user,institutionId]);
  const allowedDivisions=useMemo(()=>{if(!user)return[];if(institutionWide)return divisions;const ids=new Set(user.assignments.filter(a=>a.institution_id===institutionId&&a.role_code==="COMPARTMENT_HEAD"&&a.scope_type==="academic_compartment").map(a=>a.academic_division_id));return divisions.filter(d=>ids.has(d.id));},[user,divisions,institutionId,institutionWide]);
  useEffect(()=>{if(allowedDivisions.length&&!allowedDivisions.some(d=>d.id===divisionId))setDivisionId(allowedDivisions[0].id);},[allowedDivisions,divisionId]);
  const compartmentSubjects=subjects.filter(s=>s.academic_division_ids.includes(divisionId)).sort((a,b)=>a.name.localeCompare(b.name));
  const canonicalSubjects=[...subjects].sort((a,b)=>a.name.localeCompare(b.name));
  const divisionNames=(s:Subject)=>s.academic_division_ids.map(id=>divisions.find(d=>d.id===id)?.name).filter(Boolean).join(", ")||"Not mapped to any Academic Compartment";
  async function editSubject(s:Subject){if(busy)return;const code=window.prompt("Subject Code",s.code);if(code===null)return;const name=window.prompt("Subject Name",s.name);if(name===null)return;if(!code.trim()||!name.trim()){setNotice("Subject Code and Subject Name are required.");return;}setBusy(true);setNotice("");try{const u=await apiRequest<Subject>(`/api/v1/subjects/${s.id}`,{method:"PATCH",body:JSON.stringify({code:code.trim(),name:name.trim()})});setSubjects(c=>c.map(x=>x.id===u.id?u:x));setNotice(`${u.name} was updated successfully.`);}catch(e){setNotice(e instanceof Error?e.message:"Unable to edit subject");}finally{setBusy(false);}}
  async function removeSubject(s:Subject){if(!divisionId||busy)return;const d=divisions.find(x=>x.id===divisionId);if(!window.confirm(`Remove ${s.name} from ${d?.name??"this Academic Compartment"}?\n\nThis keeps the canonical subject in the institution.`))return;setBusy(true);setNotice("");try{await apiRequest<void>(`/api/v1/subjects/${s.id}/academic-compartments/${divisionId}`,{method:"DELETE"});setSubjects(c=>c.map(x=>x.id===s.id?{...x,academic_division_ids:x.academic_division_ids.filter(id=>id!==divisionId)}:x));setNotice(`${s.name} was removed from ${d?.name??"the Academic Compartment"}.`);}catch(e){setNotice(e instanceof Error?e.message:"Unable to remove subject");}finally{setBusy(false);}}
  async function deleteSubject(s:Subject){if(busy)return;if(!window.confirm(`PERMANENTLY DELETE ${s.code} · ${s.name} from the institution's Canonical Subject Master?\n\nThis action cannot be undone.`))return;const typed=window.prompt(`For safety, type the subject code ${s.code} to confirm permanent deletion.`);if(typed?.trim().toUpperCase()!==s.code.toUpperCase()){if(typed!==null)setNotice("Permanent deletion cancelled: subject code did not match.");return;}setBusy(true);setNotice("");try{await apiRequest<void>(`/api/v1/subjects/${s.id}`,{method:"DELETE"});setSubjects(c=>c.filter(x=>x.id!==s.id));setNotice(`${s.code} · ${s.name} was permanently deleted from the Canonical Subject Master.`);}catch(e){setNotice(e instanceof Error?e.message:"Unable to permanently delete subject");}finally{setBusy(false);}}
  const actions=(s:Subject,allowRemove:boolean)=><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button type="button" className="table-edit-button" disabled={busy} onClick={()=>editSubject(s)}>Edit</button>{allowRemove?<button type="button" className="table-edit-button" disabled={busy} onClick={()=>removeSubject(s)}>Remove</button>:null}<button type="button" disabled={busy} onClick={()=>deleteSubject(s)} style={{border:"1px solid #d92d20",background:"#fff5f5",color:"#b42318",borderRadius:8,padding:"7px 10px",fontWeight:700,cursor:busy?"not-allowed":"pointer"}}>Delete Completely</button></div>;
  return <main style={{maxWidth:1050,margin:"36px auto",padding:"0 22px",color:"#172033"}}><p style={{color:"#52617a",fontWeight:700}}>AcadPulse — Academic Intelligence &amp; Management Platform</p><h1>Manage Canonical Subjects</h1><p style={{color:"#64748b",lineHeight:1.6}}>{institutionWide?"Principal / School Admin can see the complete institution-wide Canonical Subject Master, including subjects not currently mapped to any Academic Compartment.":"Your view contains subjects available in your assigned Academic Compartment."}</p><p><Link href="/academic-responsibilities">← Back to Subjects &amp; Academic Responsibilities</Link></p>{notice?<div className="notice" style={{margin:"18px 0"}}>{notice}</div>:null}{institutions.length>1?<label style={{display:"block",marginBottom:14,fontWeight:700}}>Institution<select value={institutionId} onChange={e=>setInstitutionId(e.target.value)} style={{display:"block",width:"100%",marginTop:6,padding:10}}>{institutions.map(x=><option key={x.id} value={x.id}>{x.display_name||x.official_name}</option>)}</select></label>:null}
  {institutionWide?<section style={{background:"#fff",border:"1px solid #e1e6ef",borderRadius:14,padding:22,marginBottom:22}}><h2 style={{marginTop:0}}>Institution-wide Canonical Subject Master</h2><p style={{color:"#64748b"}}>This includes unmapped subjects. Use Delete Completely only for entries that should not exist as canonical subjects.</p>{canonicalSubjects.length?<div style={{display:"grid",gap:10}}>{canonicalSubjects.map(s=><div key={s.id} style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:16,border:"1px solid #e3e7ef",borderRadius:10,padding:"12px 14px",flexWrap:"wrap"}}><div><strong>{s.code}</strong> · {s.name}<div style={{fontSize:13,color:"#64748b",marginTop:4}}>{divisionNames(s)}</div></div>{actions(s,false)}</div>)}</div>:<p>No canonical subjects found.</p>}</section>:null}
  <label style={{display:"block",marginBottom:20,fontWeight:700}}>Academic Compartment<select value={divisionId} onChange={e=>setDivisionId(e.target.value)} style={{display:"block",width:"100%",marginTop:6,padding:10}}>{allowedDivisions.map(x=><option key={x.id} value={x.id}>{x.name} ({x.code})</option>)}</select></label><section style={{background:"#fff",border:"1px solid #e1e6ef",borderRadius:14,padding:22}}><h2 style={{marginTop:0}}>Subjects in this Academic Compartment</h2>{compartmentSubjects.length?<div style={{display:"grid",gap:10}}>{compartmentSubjects.map(s=><div key={s.id} style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:16,border:"1px solid #e3e7ef",borderRadius:10,padding:"12px 14px",flexWrap:"wrap"}}><span><strong>{s.code}</strong> · {s.name}</span>{actions(s,true)}</div>)}</div>:<p style={{color:"#64748b"}}>No canonical subjects are available in this Academic Compartment.</p>}</section></main>;
}
