"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState, type CSSProperties } from "react";

import {
  AcademicDivision,
  AcademicDivisionGradeLevel,
  AcademicResponsibilityType,
  AcademicYear,
  ClassGroup,
  CurrentUser,
  GradeLevel,
  Institution,
  StaffAcademicResponsibility,
  StaffProfile,
  Subject,
  apiRequest,
} from "../../lib/api";

type Notice = { type: "success" | "error"; text: string } | null;

const inputStyle: CSSProperties = { width: "100%", marginTop: 6, padding: "10px 12px", border: "1px solid #d8deea", borderRadius: 9, background: "#fff", color: "#172033" };
const cardStyle: CSSProperties = { background: "#fff", border: "1px solid #e1e6ef", borderRadius: 14, boxShadow: "0 8px 24px rgba(27, 42, 78, 0.06)" };
const responsibilityLabels: Record<AcademicResponsibilityType, string> = { SUBJECT_TEACHER: "Subject Teacher", CLASS_TEACHER: "Class Teacher", HOD: "HOD", OVERALL_CLASS_INCHARGE: "Overall Class Incharge" };

export default function AcademicResponsibilitiesPage() {
  const [currentUser, setCurrentUser] = useState<CurrentUser | null>(null);
  const [institutions, setInstitutions] = useState<Institution[]>([]);
  const [years, setYears] = useState<AcademicYear[]>([]);
  const [divisions, setDivisions] = useState<AcademicDivision[]>([]);
  const [grades, setGrades] = useState<GradeLevel[]>([]);
  const [mappings, setMappings] = useState<AcademicDivisionGradeLevel[]>([]);
  const [classes, setClasses] = useState<ClassGroup[]>([]);
  const [profiles, setProfiles] = useState<StaffProfile[]>([]);
  const [subjects, setSubjects] = useState<Subject[]>([]);
  const [responsibilities, setResponsibilities] = useState<StaffAcademicResponsibility[]>([]);
  const [selectedInstitutionId, setSelectedInstitutionId] = useState("");
  const [selectedYearId, setSelectedYearId] = useState("");
  const [selectedDivisionId, setSelectedDivisionId] = useState("");
  const [loaded, setLoaded] = useState(false);
  const [loadingContext, setLoadingContext] = useState(false);
  const [saving, setSaving] = useState(false);
  const [notice, setNotice] = useState<Notice>(null);
  const [subjectCode, setSubjectCode] = useState("");
  const [subjectName, setSubjectName] = useState("");
  const [staffProfileId, setStaffProfileId] = useState("");
  const [responsibilityType, setResponsibilityType] = useState<AcademicResponsibilityType>("SUBJECT_TEACHER");
  const [displayTitle, setDisplayTitle] = useState("");
  const [subjectIds, setSubjectIds] = useState<string[]>([]);
  const [gradeIds, setGradeIds] = useState<string[]>([]);
  const [classGroupIds, setClassGroupIds] = useState<string[]>([]);

  const selectedInstitution = useMemo(() => institutions.find((item) => item.id === selectedInstitutionId) ?? null, [institutions, selectedInstitutionId]);
  const selectedDivision = useMemo(() => divisions.find((item) => item.id === selectedDivisionId) ?? null, [divisions, selectedDivisionId]);
  const institutionWideSingle = Boolean(currentUser && !currentUser.is_platform_admin && institutions.length === 1);
  const canManageSubjects = useMemo(() => {
    if (!currentUser || !selectedInstitutionId || !selectedDivisionId) return false;
    if (currentUser.is_platform_admin) return true;
    return currentUser.assignments.some((a) => a.institution_id === selectedInstitutionId && ((a.scope_type === "institution" && ["PRINCIPAL", "SCHOOL_ADMIN"].includes(a.role_code)) || (a.role_code === "COMPARTMENT_HEAD" && a.scope_type === "academic_compartment" && a.academic_division_id === selectedDivisionId)));
  }, [currentUser, selectedInstitutionId, selectedDivisionId]);
  const canManageResponsibilities = canManageSubjects;
  const isCompartmentHead = useMemo(() => Boolean(currentUser?.assignments.some((a) => a.role_code === "COMPARTMENT_HEAD" && a.scope_type === "academic_compartment" && a.institution_id === selectedInstitutionId)), [currentUser, selectedInstitutionId]);
  const divisionGradeMappings = useMemo(() => mappings.filter((x) => x.academic_year_id === selectedYearId && x.academic_division_id === selectedDivisionId).sort((a,b)=>(a.sequence_no??999)-(b.sequence_no??999)), [mappings,selectedYearId,selectedDivisionId]);
  const visibleGrades = useMemo(() => { const ids=new Set(divisionGradeMappings.map(x=>x.grade_level_id)); return grades.filter(x=>ids.has(x.id)).sort((a,b)=>a.level_order-b.level_order); }, [divisionGradeMappings,grades]);
  const visibleClasses = useMemo(() => { const ids=new Set(visibleGrades.map(x=>x.id)); return classes.filter(x=>x.academic_year_id===selectedYearId&&ids.has(x.grade_level_id)).sort((a,b)=>(grades.find(g=>g.id===a.grade_level_id)?.level_order??999)-(grades.find(g=>g.id===b.grade_level_id)?.level_order??999)||a.section_code.localeCompare(b.section_code,undefined,{numeric:true})); }, [classes,grades,selectedYearId,visibleGrades]);
  const visibleProfiles = useMemo(() => profiles.filter(x=>x.is_active&&x.staff_type==="TEACHING"&&x.academic_division_ids.includes(selectedDivisionId)).sort((a,b)=>a.full_name.localeCompare(b.full_name)), [profiles,selectedDivisionId]);
  const visibleSubjects = useMemo(() => subjects.filter(x=>x.academic_division_ids.includes(selectedDivisionId)).sort((a,b)=>a.name.localeCompare(b.name)), [subjects,selectedDivisionId]);
  const gradeName=(id:string)=>grades.find(x=>x.id===id)?.display_name??"Unknown grade";
  const className=(id:string)=>classes.find(x=>x.id===id)?.display_name??"Unknown section";
  const subjectLabel=(id:string)=>{const x=subjects.find(s=>s.id===id);return x?`${x.name} (${x.code})`:"Unknown subject";};
  function toggleValue(v:string, values:string[], setter:(n:string[])=>void){setter(values.includes(v)?values.filter(x=>x!==v):[...values,v]);}
  function resetResponsibilityForm(type:AcademicResponsibilityType=responsibilityType){setStaffProfileId("");setResponsibilityType(type);setDisplayTitle("");setSubjectIds([]);setGradeIds([]);setClassGroupIds([]);}

  async function loadInstitutionContext(id:string){if(!id)return;setLoadingContext(true);setNotice(null);try{const [yd,dd,gd,md,cd,sd,sub]=await Promise.all([apiRequest<AcademicYear[]>(`/api/v1/academic-years?institution_id=${id}`),apiRequest<AcademicDivision[]>(`/api/v1/academic-divisions?institution_id=${id}`),apiRequest<GradeLevel[]>(`/api/v1/grade-levels?institution_id=${id}`),apiRequest<AcademicDivisionGradeLevel[]>(`/api/v1/academic-division-grade-levels?institution_id=${id}`),apiRequest<ClassGroup[]>(`/api/v1/class-groups?institution_id=${id}`),apiRequest<StaffProfile[]>(`/api/v1/staff-profiles?institution_id=${id}&include_inactive=false`),apiRequest<Subject[]>(`/api/v1/subjects?institution_id=${id}`)]);setYears(yd);setDivisions(dd);setGrades(gd);setMappings(md);setClasses(cd);setProfiles(sd);setSubjects(sub);setSelectedYearId(c=>yd.some(x=>x.id===c)?c:yd.find(x=>x.is_current)?.id??yd[0]?.id??"");setSelectedDivisionId(c=>dd.some(x=>x.id===c)?c:dd[0]?.id??"");}catch(e){setNotice({type:"error",text:e instanceof Error?e.message:"Unable to load academic responsibility context"});}finally{setLoadingContext(false);}}
  async function loadResponsibilities(i:string,y:string,d:string){if(!i||!y||!d){setResponsibilities([]);return;}try{setResponsibilities(await apiRequest<StaffAcademicResponsibility[]>(`/api/v1/staff-responsibilities?institution_id=${i}&academic_year_id=${y}&academic_division_id=${d}`));}catch(e){setNotice({type:"error",text:e instanceof Error?e.message:"Unable to load academic responsibilities"});}}
  useEffect(()=>{Promise.all([apiRequest<CurrentUser>("/api/v1/auth/me"),apiRequest<Institution[]>("/api/v1/institutions")]).then(([u,s])=>{setCurrentUser(u);setInstitutions(s);setSelectedInstitutionId(s[0]?.id??"");}).catch((e:Error)=>setNotice({type:"error",text:e.message})).finally(()=>setLoaded(true));},[]);
  useEffect(()=>{if(!currentUser||!selectedInstitutionId)return;resetResponsibilityForm();loadInstitutionContext(selectedInstitutionId).catch(()=>undefined);},[currentUser,selectedInstitutionId]);
  useEffect(()=>{resetResponsibilityForm();loadResponsibilities(selectedInstitutionId,selectedYearId,selectedDivisionId).catch(()=>undefined);},[selectedInstitutionId,selectedYearId,selectedDivisionId]);

  async function createSubject(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selectedInstitutionId||!selectedDivisionId||!canManageSubjects)return;setSaving(true);setNotice(null);try{const c=await apiRequest<Subject>("/api/v1/subjects",{method:"POST",body:JSON.stringify({institution_id:selectedInstitutionId,academic_division_id:selectedDivisionId,code:subjectCode.trim(),name:subjectName.trim()})});setSubjects(cur=>[...cur.filter(x=>x.id!==c.id),c].sort((a,b)=>a.name.localeCompare(b.name)));setSubjectCode("");setSubjectName("");setNotice({type:"success",text:`${c.name} is now available in ${selectedDivision?.name??"the selected Academic Compartment"}.`});}catch(e){setNotice({type:"error",text:e instanceof Error?e.message:"Unable to create subject"});}finally{setSaving(false);}}
  async function removeSubject(subject:Subject){if(!canManageSubjects||!selectedDivisionId)return;if(!window.confirm(`Remove ${subject.name} (${subject.code}) from ${selectedDivision?.name??"this Academic Compartment"}?\n\nThe canonical subject will not be deleted institution-wide.`))return;setSaving(true);setNotice(null);try{await apiRequest<void>(`/api/v1/subjects/${subject.id}/academic-compartments/${selectedDivisionId}`,{method:"DELETE"});setSubjects(cur=>cur.map(x=>x.id===subject.id?{...x,academic_division_ids:x.academic_division_ids.filter(id=>id!==selectedDivisionId)}:x));setSubjectIds(cur=>cur.filter(id=>id!==subject.id));setNotice({type:"success",text:`${subject.name} has been removed from ${selectedDivision?.name??"the selected Academic Compartment"}.`});}catch(e){setNotice({type:"error",text:e instanceof Error?e.message:"Unable to remove subject"});}finally{setSaving(false);}}
  async function createResponsibility(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!canManageResponsibilities||!staffProfileId||!selectedInstitutionId||!selectedYearId||!selectedDivisionId)return;let fs=subjectIds,fg=gradeIds,fc=classGroupIds;if(responsibilityType==="SUBJECT_TEACHER"){fs=subjectIds.slice(0,1);fg=[];}else if(responsibilityType==="CLASS_TEACHER"){fs=[];fg=[];fc=classGroupIds.slice(0,1);}else if(responsibilityType==="HOD"){fg=[];fc=[];}else{fs=[];fc=[];}setSaving(true);setNotice(null);try{const c=await apiRequest<StaffAcademicResponsibility>("/api/v1/staff-responsibilities",{method:"POST",body:JSON.stringify({staff_profile_id:staffProfileId,institution_id:selectedInstitutionId,academic_year_id:selectedYearId,academic_division_id:selectedDivisionId,responsibility_type:responsibilityType,display_title:displayTitle.trim()||null,subject_ids:fs,grade_level_ids:fg,class_group_ids:fc})});setResponsibilities(cur=>[...cur,c]);resetResponsibilityForm(responsibilityType);setNotice({type:"success",text:`${c.staff_display_name}'s ${responsibilityLabels[c.responsibility_type]} responsibility has been saved.`});}catch(e){setNotice({type:"error",text:e instanceof Error?e.message:"Unable to create academic responsibility"});}finally{setSaving(false);}}
  async function removeResponsibility(item:StaffAcademicResponsibility){if(!canManageResponsibilities)return;setSaving(true);setNotice(null);try{await apiRequest<void>(`/api/v1/staff-responsibilities/${item.id}`,{method:"DELETE"});setResponsibilities(cur=>cur.filter(x=>x.id!==item.id));setNotice({type:"success",text:`${item.staff_display_name}'s responsibility has been removed.`});}catch(e){setNotice({type:"error",text:e instanceof Error?e.message:"Unable to remove academic responsibility"});}finally{setSaving(false);}}
  function targetSummary(item:StaffAcademicResponsibility){if(item.responsibility_type==="HOD")return item.subject_ids.map(subjectLabel).join(", ");if(item.responsibility_type==="OVERALL_CLASS_INCHARGE")return item.grade_level_ids.map(gradeName).join(", ");if(item.responsibility_type==="CLASS_TEACHER")return item.class_group_ids.map(className).join(", ");return `${item.subject_ids.map(subjectLabel).join(", ")} → ${item.class_group_ids.map(className).join(", ")}`;}

  if(!loaded)return <main style={{maxWidth:1100,margin:"48px auto",padding:24}}><p>Loading Subjects &amp; Academic Responsibilities…</p></main>;
  if(!currentUser)return <main style={{maxWidth:800,margin:"48px auto",padding:24}}><h1>Academic responsibilities unavailable</h1><p>{notice?.text||"Please sign in to AcadPulse first."}</p><Link href="/">Return to AcadPulse</Link></main>;
  return <main style={{maxWidth:1240,margin:"32px auto 64px",padding:"0 22px"}}>
    <header style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:20,flexWrap:"wrap",marginBottom:24}}><div><p style={{margin:"0 0 6px",color:"#52617a",fontWeight:700}}>AcadPulse — Academic Intelligence &amp; Management Platform</p><h1 style={{margin:0,fontSize:"clamp(1.75rem, 4vw, 2.5rem)",color:"#172033"}}>Subjects &amp; Academic Responsibilities</h1><p style={{maxWidth:820,color:"#5d687b",lineHeight:1.6}}>Compartment Heads maintain the subjects and staff responsibilities for their assigned Academic Compartment. Principal / School Admin retain institution-wide oversight and override access.</p></div><Link className="secondary-button" href="/">Back to School Foundation</Link></header>
    {notice?<div className={`notice ${notice.type}`} style={{marginBottom:18}}>{notice.text}</div>:null}
    <section style={{...cardStyle,padding:20,marginBottom:20}}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit, minmax(210px, 1fr))",gap:16,alignItems:"end"}}><div><p style={{margin:"0 0 4px",fontSize:".78rem",fontWeight:800,color:"#64748b",textTransform:"uppercase",letterSpacing:".05em"}}>Institution</p>{institutionWideSingle&&selectedInstitution?<strong>{selectedInstitution.display_name||selectedInstitution.official_name}</strong>:<select value={selectedInstitutionId} onChange={e=>setSelectedInstitutionId(e.target.value)} style={inputStyle}><option value="">Select institution</option>{institutions.map(x=><option key={x.id} value={x.id}>{x.display_name||x.official_name}</option>)}</select>}</div><label style={{fontWeight:700,color:"#354157"}}>Academic Year<select value={selectedYearId} onChange={e=>setSelectedYearId(e.target.value)} style={inputStyle} disabled={!selectedInstitutionId}><option value="">Select academic year</option>{years.map(x=><option key={x.id} value={x.id}>{x.name}{x.is_current?" — Current":""}</option>)}</select></label><label style={{fontWeight:700,color:"#354157"}}>Academic Compartment<select value={selectedDivisionId} onChange={e=>setSelectedDivisionId(e.target.value)} style={inputStyle} disabled={!selectedInstitutionId}><option value="">Select Academic Compartment</option>{divisions.map(x=><option key={x.id} value={x.id}>{x.name} ({x.code})</option>)}</select></label><div><p style={{margin:"0 0 4px",fontSize:".78rem",fontWeight:800,color:"#64748b",textTransform:"uppercase",letterSpacing:".05em"}}>Your access</p><strong>{canManageSubjects&&canManageResponsibilities?(isCompartmentHead?"Compartment Subject Master + responsibility management":"Institution oversight + compartment management"):"Academic responsibility view"}</strong></div></div></section>
    <section style={{...cardStyle,padding:18,marginBottom:20,background:"#f8faff"}}><strong>Canonical subjects stay separate from timetable synchronization blocks.</strong><p style={{marginBottom:0,color:"#52617a",lineHeight:1.6}}>Create Mathematics and IP as separate subjects. Labels such as MATHS / IP, MATHS / H.S / IP, BIO / C.S and LANG II are handled later as instructional groups / parallel timetable blocks — not as Subject Master entries.</p></section>
    <section style={{...cardStyle,padding:22,marginBottom:22}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><h2 style={{margin:0}}>Canonical Subject Master</h2><p style={{margin:"6px 0 0",color:"#64748b"}}>{selectedDivision?`${visibleSubjects.length} active subjects available in ${selectedDivision.name}.`:"Select an Academic Compartment to manage its subjects."}</p></div>{isCompartmentHead&&canManageSubjects?<span style={{color:"#64748b",fontWeight:700}}>You manage subjects only for your assigned Academic Compartment.</span>:null}</div>
      {canManageSubjects?<form onSubmit={createSubject} style={{display:"grid",gridTemplateColumns:"minmax(150px, .5fr) minmax(240px, 1fr) auto",gap:14,alignItems:"end",marginTop:18}}><label style={{fontWeight:700,color:"#354157"}}>Subject Code<input value={subjectCode} onChange={e=>setSubjectCode(e.target.value)} required maxLength={50} placeholder="MATH" style={inputStyle}/></label><label style={{fontWeight:700,color:"#354157"}}>Subject Name<input value={subjectName} onChange={e=>setSubjectName(e.target.value)} required maxLength={120} placeholder="Mathematics" style={inputStyle}/></label><button className="primary-button" disabled={saving||!selectedDivisionId}>Add Subject</button></form>:null}
      <div style={{marginTop:18,display:"flex",flexWrap:"wrap",gap:8}}>{visibleSubjects.length?visibleSubjects.map(subject=><span key={subject.id} style={{display:"inline-flex",alignItems:"center",gap:7,border:"1px solid #dfe5ef",borderRadius:999,padding:"5px 6px 5px 10px",background:"#fff",color:"#354157"}}><span><strong>{subject.code}</strong> · {subject.name}</span>{canManageSubjects?<button type="button" onClick={()=>removeSubject(subject)} disabled={saving} title={`Remove ${subject.name} from ${selectedDivision?.name??"this Academic Compartment"}`} style={{border:"1px solid #f1b8b8",background:"#fff5f5",color:"#a32626",borderRadius:999,padding:"3px 8px",cursor:saving?"not-allowed":"pointer",fontWeight:700}}>Remove</button>:null}</span>):<p style={{color:"#64748b"}}>No canonical subjects have been added to this Academic Compartment yet.</p>}</div>
    </section>
    <section style={{...cardStyle,padding:22,marginBottom:22}}><h2 style={{margin:0}}>Assign Academic Responsibility</h2><p style={{margin:"6px 0 0",color:"#64748b",lineHeight:1.6}}>{selectedDivision?`Assignments created here are scoped to ${selectedDivision.name}.`:"Select an Academic Compartment first."} Teachers do not need AcadPulse login accounts; responsibilities are attached to their Staff Profiles.</p>
      {canManageResponsibilities?<form onSubmit={createResponsibility} style={{marginTop:20,display:"grid",gap:18}}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit, minmax(220px, 1fr))",gap:14}}><label style={{fontWeight:700,color:"#354157"}}>Staff Profile<select value={staffProfileId} onChange={e=>setStaffProfileId(e.target.value)} required style={inputStyle}><option value="">Select teacher</option>{visibleProfiles.map(x=><option key={x.id} value={x.id}>{x.full_name}{x.employee_code?` — ${x.employee_code}`:""}</option>)}</select></label><label style={{fontWeight:700,color:"#354157"}}>Responsibility<select value={responsibilityType} onChange={e=>resetResponsibilityForm(e.target.value as AcademicResponsibilityType)} style={inputStyle}>{Object.entries(responsibilityLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label style={{fontWeight:700,color:"#354157"}}>Display Title <span style={{fontWeight:500,color:"#7b8798"}}>(optional)</span><input value={displayTitle} onChange={e=>setDisplayTitle(e.target.value)} maxLength={120} placeholder="e.g. HOD of Languages" style={inputStyle}/></label></div>
      {(responsibilityType==="SUBJECT_TEACHER"||responsibilityType==="HOD")?<div><strong>Subject{responsibilityType==="HOD"?"s":""}</strong><div style={{marginTop:8,display:"grid",gridTemplateColumns:"repeat(auto-fit, minmax(210px, 1fr))",gap:8}}>{visibleSubjects.map(s=><label key={s.id} style={{border:"1px solid #e1e6ef",borderRadius:9,padding:"9px 10px"}}><input type={responsibilityType==="SUBJECT_TEACHER"?"radio":"checkbox"} name="subject" checked={subjectIds.includes(s.id)} onChange={()=>responsibilityType==="SUBJECT_TEACHER"?setSubjectIds([s.id]):toggleValue(s.id,subjectIds,setSubjectIds)}/> {s.name}</label>)}</div></div>:null}
      {responsibilityType==="OVERALL_CLASS_INCHARGE"?<div><strong>Grades</strong><div style={{marginTop:8,display:"grid",gridTemplateColumns:"repeat(auto-fit, minmax(160px, 1fr))",gap:8}}>{visibleGrades.map(g=><label key={g.id} style={{border:"1px solid #e1e6ef",borderRadius:9,padding:"9px 10px"}}><input type="checkbox" checked={gradeIds.includes(g.id)} onChange={()=>toggleValue(g.id,gradeIds,setGradeIds)}/> {g.display_name}</label>)}</div></div>:null}
      {(responsibilityType==="SUBJECT_TEACHER"||responsibilityType==="CLASS_TEACHER")?<fieldset style={{border:"1px solid #dfe5ef",borderRadius:12,padding:14}}><legend style={{fontWeight:700}}>{responsibilityType==="CLASS_TEACHER"?"Class Section":"Teaching Sections"}</legend><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit, minmax(160px, 1fr))",gap:8}}>{visibleClasses.map(c=><label key={c.id} style={{border:"1px solid #e1e6ef",borderRadius:9,padding:"9px 10px"}}><input type={responsibilityType==="CLASS_TEACHER"?"radio":"checkbox"} name={responsibilityType==="CLASS_TEACHER"?"class-section":undefined} checked={classGroupIds.includes(c.id)} onChange={()=>responsibilityType==="CLASS_TEACHER"?setClassGroupIds([c.id]):toggleValue(c.id,classGroupIds,setClassGroupIds)}/> {c.display_name}</label>)}</div></fieldset>:null}
      <button className="primary-button" disabled={saving||loadingContext}>Save Responsibility</button></form>:<p style={{marginTop:18,color:"#64748b"}}>You have read-only access to responsibilities in this Academic Compartment.</p>}</section>
    <section style={{...cardStyle,padding:22}}><h2 style={{margin:0}}>Current Responsibilities</h2><p style={{color:"#64748b"}}>{responsibilities.length} active assignment{responsibilities.length===1?"":"s"} in this year and Academic Compartment.</p>{responsibilities.length?<div style={{display:"grid",gap:10}}>{responsibilities.map(item=><div key={item.id} style={{border:"1px solid #e1e6ef",borderRadius:10,padding:12,display:"flex",justifyContent:"space-between",gap:14,alignItems:"center",flexWrap:"wrap"}}><div><strong>{item.staff_display_name}</strong><div style={{color:"#52617a",marginTop:4}}>{responsibilityLabels[item.responsibility_type]} · {targetSummary(item)}{item.display_title?` · ${item.display_title}`:""}</div></div>{canManageResponsibilities?<button type="button" className="secondary-button" disabled={saving} onClick={()=>removeResponsibility(item)}>Remove</button>:null}</div>)}</div>:<p style={{color:"#64748b"}}>No responsibilities have been assigned in this context yet.</p>}</section>
  </main>;
}
